### ISSUE TITLE
update CONTRIBUTING.md

### ISSUE THREAD

**Issue by cbeleites** [eoduniyi/hyperSpec.skeleton#16]
... to tell that we are slowly moving to MIT license.

**Comment by bryanhanson** [comment]
I went to fix this, but then I decided I wasn't sure of the language we needed.... something like "hyperSpec and its associated repos were originally licensed under GPL-3 but as of June 2020 we are migrating to the MIT license.  All future contributions will be MIT licensed" Thoughts?

**Comment by cbeleites** [comment]
Sounds good to me

**Comment by bryanhanson** [comment]
Fixed language in `CONTRIBUTING.md` and put the MIT license language into `LICENSE`.  See https://github.com/r-hyperspec/pkg-skeleton/commit/f077e80e1a19a728582f4c3dc9fbe9e666a7499d
