### ISSUE TITLE
Update CI workflow for Linux

### ISSUE THREAD

**Issue by GegznaV** [eoduniyi/hyperSpec.skeleton#17]
GH actions issues this warning:
![image](https://user-images.githubusercontent.com/12725868/122041143-4ee68d00-cde1-11eb-9d4e-7f9f2500fb13.png)

> **Annotations**
>
> 1 warning
> 
> Insert package (drat) : .github#L1
>
> The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead. For more details see https://github.com/actions/virtual-environments/issues/3287

We should update CI workflow in `hySpc` repos. There are some specifics in the main `hyperSpec` repo, so a separate issue will be opened there too.

**Comment by bryanhanson** [comment]
Fixed by https://github.com/r-hyperspec/pkg-skeleton/commit/6f48374315c4f64739a07016b25d234160b6a90a (here, and all other packages; note that there seems to be a GHA configuration problem for R-release, they seem to be missing `stringi`)
