### ISSUE TITLE
Do we have .Rbuildignore correct?

### ISSUE THREAD

**Issue by bryanhanson** [eoduniyi/hyperSpec.skeleton#18]
@GegznaV would  you please look at `.Rbuildignore` on the `develop` branch and see if it looks OK?  I ran a script which got `.Rbuildignore` from every repo and then grabbed all the unique values.  I then manually went through it to organize.  I dropped some entries that did not seem appropriate (really, the accumulated entries were a mess).  If we do the best we can here, then when we actually deploy it we may still find some entries to add.  I'm attaching the list of unique values for you to review.
[Rbuildignore.txt](https://github.com/r-hyperspec/pkg-skeleton/files/6904758/Rbuildignore.txt)

**Comment by GegznaV** [comment]
Can we have sections for **common** build-ignored files (this section should be synced across repos) and **package specific** (must not be synced)? We have something similar in drat file which lists available versions of the packages to download: here only some specific parts of the file get updated. 

[This answer](https://community.rstudio.com/t/comments-in-rbuildignore/109320) says, that we can have comments in Rbuildignore files, so we can create sections. 

Here I sorted the entries in the attached file to groups "common", "package-specific", then " where do we use these?" (I do not know if these should go to "package-specific" or should be deleted) and "remove" (these files should not be present in the repos anymore).

```gitignore
### common ###

^.*\.Rproj$
^\.Rproj\.user$
^\.github$

^.codecov\.yml$
^codecov\.yml$
  
^_pkgdown\.yml$
^pkgdown$
  
^NEWS\.html$
^CONTRIBUTING\.md$
  
^data-raw$
^docs$
^_tmp

Rplots.pdf



### package-specific ###
  
^inst/extdata/chondro\.gz$
^inst/extdata/winspec.pdf$


### where do we use these? ###
# maybe should go to section "package-specific" 

^github-helpers$
tests/testthat/fileio


### remove ###
  
^appveyor\.yml$
^.appveyor\.yml$
^\.travis\.yml$
^Vignettes-Rnw$
Makefile
^docs
```

And for the first time, we should do the synchronization of some (or all) files manually checking if they have anything special. Some of the "special" should be kept but most (especially in ".gitignore") should be removed in order not to clutter the file. In some ".gitignore" the order of the rows in the file matters (especially where `!` exists).

**Comment by GegznaV** [comment]
To make life easier, we can synchronize the whole file, just have section `### package-specific ###` in it. E.g.:

```gitignore
### common ###

# R projects
^.*\.Rproj$
^\.Rproj\.user$

# Github
^\.github$

# Codecov
^.codecov\.yml$
^codecov\.yml$

# pkgdown
^_pkgdown\.yml$
^pkgdown$
 ^docs$

# Top-level files
^NEWS\.html$
^CONTRIBUTING\.md$

 # Other directories
^data-raw$
^_tmp

# Unwanted files
Rplots.pdf

### package-specific ###
  
^inst/extdata/chondro\.gz$
^inst/extdata/winspec.pdf$

^github-helpers$
tests/testthat/fileio
```

**NOTE:** Just I'm not sure if blank lines are legal in `.Rbuildignore`.

**Comment by GegznaV** [comment]
To make myself more clear:

> And for the first time, we should do the synchronization of some (or all) files manually checking if they have anything special. Some of the "special" should be kept but most (especially in ".gitignore") should be removed in order not to clutter the file. In some ".gitignore" the order of the rows in the file matters (especially where ! exists).

For `.Rbuildignore` we may have a section for package-specific things, and for `.gitignore` we everything should be the same across all package repos.

**Comment by GegznaV** [comment]
I think, the following lines in `.RBuildignore` causes some R-CMD-check warnings. I'll check this and remove if needed.

```gitignore
# Other/Broad
^.*\.html
^.*\.pdf
```

Issues:
![image](https://user-images.githubusercontent.com/12725868/144063513-a16bb5b9-3a30-465e-9f11-15f40fe72aca.png)

![image](https://user-images.githubusercontent.com/12725868/144063598-f2b37906-9305-4f38-87db-724dd083f50c.png)
