### ISSUE TITLE
Do we have .gitignore correct?

### ISSUE THREAD

**Issue by bryanhanson** [eoduniyi/hyperSpec.skeleton#19]
@GegznaV would  you please look at `.gitignore` on the `develop` branch and see if it looks OK?  I ran a script which got `.gitignore` from every repo and then grabbed all the unique values.  I then manually went through it to organize.  I dropped some entries that did not seem appropriate (really, the accumulated entries were a mess).  If we do the best we can here, then when we actually deploy it we may still find some entries to add.  I'm attaching the list of unique values for you to review.
[Gitignore.txt](https://github.com/r-hyperspec/pkg-skeleton/files/6904763/Gitignore.txt)

**Comment by GegznaV** [comment]
In short: currently no. I will look into this later.

**Comment by GegznaV** [comment]
There are several `.gitignore` files. The contents of the file in the main dir should be:
```gitignore
# History files
.Rhistory
.Rapp.history

# Session Data files
.RData
.Ruserdata

# Example code in package build process
*-Ex.R

# Mac directory files
*.DS_Store

# RStudio files
.Rproj.user
*.Rproj

# Local pkgdown files
docs/

# Unit tests
tests/testthat/fileio
tests/testthat/Rplots.pdf

# Vignettes
vignettes/*-pkg.bib
vignettes/*.html
vignettes/*.R
vignettes/fileio
vignettes/resources/*.bib

# Documentation
man/*.Rd
NAMESPACE
NEWS.html
README.html

# Other
_tmp/

```

If anything extra is needed, it should be discussed separately.

**Comment by GegznaV** [comment]
Related comment: https://github.com/r-hyperspec/pkg-skeleton/issues/18#issuecomment-889695873

**Comment by GegznaV** [comment]
Due to changes in `vdiffr` 1.0.0, dir `tests/testthat/_snaps/attached/` must be tracked (I'll update my messages above).

**Comment by GegznaV** [comment]
OK, I see that all `.pdf` and `.html` files are not tracked in `pkg-skeleton`:

- In some repos there are PDF manuals, that should not be git ignored. But they should be Rbuild ignored. So I'll remove this.
- I do not know any HTML files, so this is OK for me (al least for now).
