### ISSUE TITLE
consistent set of labels across derived packages

### ISSUE THREAD

**Issue by cbeleites** [eoduniyi/hyperSpec.skeleton#2]
... this is not strictly part of the skeleton package, but I think it would be good if we could have a consistent set of labels (including colors) for the derived packages and **hyperSpec**

- [x] have the "master" set of labels here in the skeleton project  
  for a start, copy the ones from [**hyperSpec**](https://github.com/cbeleites/hyperSpec/issues/labels)
- [x] make a code snippet/shell script that fetches them and pushes them into derived repository, see [github API description](https://developer.github.com/v3/issues/labels)

**Comment by eoduniyi** [comment]
Okay, the package skeleton now has a .json file with all of the labels (copied the ones from hyperSpec) so the shell script that will attach the skeleton labels will look like this:

This assumes the user has [github-labels](https://github.com/popomore/github-labels) installed globally and also has **Personal access tokens**:

    # Make sure github-labels node package is installed
    npm install github-labels -g

    # Get Github username and repo name
    echo "enter username and name of derived package repository (username/repo)"
    read pkg_repo
    
    # Get personal access tokens
    echo "enter Personal access tokens"
    read token
    
    # Pass the skeleton labels to the derived package repo
    labels -c hyperSpec.skeleton.labels.json pkg_repo -t token

**Comment by eoduniyi** [comment]
> Okay, the package skeleton now has a .json file with all of the labels (copied the ones from hyperSpec) so the shell script that will attach the skeleton labels will look like this:
> 
> This assumes the user has [github-labels](https://github.com/popomore/github-labels) installed globally and also has **Personal access tokens**:
> 
> ```
> # Make sure github-labels node package is installed
> npm install github-labels -g
> 
> # Get Github username and repo name
> echo "enter username and name of derived package repository (username/repo)"
> read pkg_repo
> 
> # Get personal access tokens
> echo "enter Personal access tokens"
> read token
> 
> # Pass the skeleton labels to the derived package repo
> labels -c hyperSpec.skeleton.labels.json pkg_repo -t token
> ```

This executable would come shipped with the template repo as the file: get_skeleton_labels.sh or something more generic to capture other configuration processes (e.g., get_all_skeleton_templates.sh)

**Comment by eoduniyi** [comment]
This was closed by PR #4
